# Generated by Django 5.2 on 2025-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dian_link', models.CharField(blank=True, help_text='Link received from the DIAN into the email', max_length=255)),
                ('from_date', models.DateField(help_text='Date from which the invoice will be downloaded')),
                ('to_date', models.DateField(help_text='Date until which the invoice will be downloaded')),
                ('invoice_type', models.CharField(choices=[('electronic_invoice', 'Factura electronica de venta'), ('received_invoice', 'Recibidos'), ('sent_invoice', 'Enviados')], default='electronic_invoice', help_text='Type of invoice to download', max_length=50)),
                ('invoices_downloaded', models.BooleanField(default=False, help_text='Indicates if the invoice has been downloaded')),
                ('invoices_processed', models.BooleanField(default=False, help_text='Indicates if the invoice has been processed')),
                ('invoices_registered', models.BooleanField(default=False, help_text='Indicates if the invoice has been registered in Odoo')),
                ('invoices_notification', models.BooleanField(default=False, help_text='Indicates if the invoice has been notified to the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
