# Generated by Django 5.2 on 2025-05-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(help_text='File of the invoice downloaded', upload_to='invoices/')),
                ('invoice_pdf', models.FileField(help_text='File of the invoice downloaded in PDF', upload_to='invoices/pdf/')),
                ('invoice_processed', models.FileField(help_text='File of the invoice processed like CSV', upload_to='invoices/processed/')),
                ('invoice_type', models.CharField(choices=[('electronic_invoice', 'Factura electronica de venta'), ('received_invoice', 'Recibidos'), ('sent_invoice', 'Enviados')], default='electronic_invoice', help_text='Type of invoice to download', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_download', models.ForeignKey(help_text='NextDownload object to which the invoice belongs', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.nextdownload')),
            ],
        ),
    ]
