# Generated by Django 5.2 on 2025-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rx_odoo_invoice',
            field=models.JSONField(blank=True, help_text='JSON field to store the invoice created in Odoo', null=True),
        ),
    ]
