# Generated by Django 5.2 on 2025-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_rx_odoo_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='registered_in_odoo',
            field=models.BooleanField(default=False, help_text='Indicates if the invoice has been registered in Odoo'),
        ),
    ]
