# Generated by Django 5.2 on 2025-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_registered_in_odoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextdownload',
            name='processing_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='Status of the invoice processing', max_length=20),
        ),
    ]
