# Generated by Django 5.2 on 2025-06-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_nextdownload_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date of the invoice downloaded', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Number of the invoice downloaded', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date of the invoice downloaded', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, help_text='Purchase order number of the invoice downloaded', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción')),
                ('unit_measurement', models.CharField(blank=True, help_text='Unidad de medida del producto (U/M)', max_length=50)),
                ('quantity', models.FloatField(default=0.0, help_text='Cantidad')),
                ('unit_price', models.FloatField(default=0.0, help_text='Precio unitario')),
                ('discount_detail', models.FloatField(default=0.0, help_text='Descuento detalle')),
                ('surcharge_detail', models.FloatField(default=0.0, help_text='Recargo detalle')),
                ('iva', models.FloatField(default=0.0, help_text='Valor IVA')),
                ('iva_percentage', models.FloatField(default=0.0, help_text='Porcentaje IVA')),
                ('inc', models.FloatField(default=0.0, help_text='Valor INC')),
                ('inc_percentage', models.FloatField(default=0.0, help_text='Porcentaje INC')),
                ('unit_sale_price', models.FloatField(default=0.0, help_text='Precio unitario de venta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Invoice to which the product belongs', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
