# Generated by Django 5.2 on 2025-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_due_date_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rx_odoo_invoice_error',
            field=models.TextField(blank=True, help_text='Error message if the invoice could not be registered in Odoo', null=True),
        ),
    ]
