# Generated by Django 5.2 on 2025-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_rx_odoo_invoice_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_processed',
            field=models.FileField(blank=True, help_text='File of the invoice processed like CSV', null=True, upload_to='invoices/processed/'),
        ),
    ]
