# Generated by Django 5.2 on 2025-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_invoice_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cufe',
            field=models.CharField(blank=True, help_text='CUFE of the invoice downloaded', max_length=150, null=True),
        ),
    ]
