# Generated by Django 5.2 on 2025-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_cufe'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='Name of the entity that issued the invoice', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_nit',
            field=models.CharField(blank=True, help_text='NIT of the entity that issued the invoice', max_length=50, null=True),
        ),
    ]
