# Generated by Django 5.2 on 2025-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_issuer_name_invoice_issuer_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('registered_complete', 'Registered Complete'), ('registered_but_not_move_id', 'Registered But Not Move Id'), ('registered_but_not_attachment', 'Registered But Not Attachment'), ('problem_not_in_odoo', 'Problem Not In Odoo'), ('problem_partner_not_created', 'Problem Partner Not Created'), ('problem_with_factos', 'Problem With Factos'), ('problem_in_odoo', 'Problem With Odoo')], default='problem_not_in_odoo', max_length=50),
        ),
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('move_id', models.CharField(primary_key=True, serialize=False)),
                ('invoice', models.ManyToManyField(to='invoice.invoice')),
            ],
        ),
    ]
