x-default-config:
  &x-default-config
  image: '${IMAGE}'
  restart: always
  env_file:
    - .env
  working_dir: /home/app/factos

networks:
  factos_network:
    name: factos_network


services:

  factos:
    <<: *x-default-config
    command: gunicorn factos.wsgi:application --name factos_gunicorn --workers 1 --timeout 120 --bind 0.0.0.0:8000 --log-level=debug --log-file=/home/app/logs/factos.log --forwarded-allow-ips '*'
    volumes:
      - .:/home/app/factos
      - ./static:/home/app/static
      - ./media:/home/app/media
      - ./logs:/home/app/logs
    networks:
      - factos_network

  celery:
    <<: *x-default-config
    volumes:
      - .:/home/app/factos
      - ./media:/home/app/media
      - ./logs:/home/app/logs
    command: celery -A factos worker -l INFO --queues=invoice_processing,celery
    networks:
      - factos_network

  celerybeat:
    <<: *x-default-config
    volumes:
      - .:/home/app/factos
      - ./media:/home/app/media
      - ./logs:/home/app/logs
    command: celery -A factos beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - factos_network

  # NGINX: Reverse proxy for the application
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '81:80'
    depends_on:
      - factos
    volumes:
      - ./nginx:/etc/nginx/conf.d # Nginx configuration
      - ./static:/home/app/static # Static files
      - ./media:/home/app/media # Media files
    networks:
      - factos_network

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - ../redis_volume:/data
    networks:
      - factos_network

  # discord_bot:
  #   <<: *x-default-config
  #   volumes:
  #     - ./logs:/home/app/logs
  #     - .:/home/app/factos
  #     - ./static:/home/app/static
  #     - ./media:/home/app/media
  #   command: python discord_bot.py >> /home/app/logs/discord_bot.log
  #   networks:
  #     - factos_network