"""
Django settings for factos project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import os
from dotenv import load_dotenv

dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x@pvoyrf%i_^m&m03l=wvn4qfe7+ohz_1h10p*tkd_(f^3wd8o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv('DJANGO_DEBUG', True))

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

# THIRD PARTY APPS
INSTALLED_APPS += [
    'django_celery_results',
    'rangefilter',
    'django_celery_beat',
    'django_extensions',
]

# OWN APPS
INSTALLED_APPS += [
    'emails_reader',
    'invoice',
    'elastic_logging',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'factos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'factos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'


# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_URL_PUBLIC = 'public'
MEDIA_HOST = os.getenv('MEDIA_HOST', '')



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# OWN CONFIGURATION
DIAN_LINK = os.getenv('DIAN_LINK', 'https://example.com/dian')
SHOW_BROWSER = bool(os.getenv('SHOW_BROWSER'))


# Celery
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_RESULT_EXTENDED = True


CONFIG_GENAI = {
    'AUTH_URL': os.getenv('GENAI_AUTH_URL', 'https://auth.unergy.io/auth/login/'),
    'AUTH_USERNAME': os.getenv('GENAI_AUTH_USERNAME'),
    'AUTH_PASSWORD': os.getenv('GENAI_AUTH_PASSWORD'),
    'API_KEY_URL': os.getenv('GENAI_API_KEY_URL', 'https://originabot.uner.gy/api/genai/api_key/get_best_key/'),
    'TOKEN_USAGE_URL': os.getenv('GENAI_TOKEN_USAGE_URL', 'https://originabot.uner.gy/api/genai/api_key/{api_key_id}/add_usage/'),
    'DEFAULT_API_KEY': os.getenv('GENAI_DEFAULT_API_KEY', None),
}


# Odoo configuration
CONFIG_ODOO = {
    'HOST': os.getenv('ODOO_HOST', 'https://example.com'),
    'DATABASE': os.getenv('ODOO_DATABASE', 'database_name'),
    'USERNAME': os.getenv('ODOO_USERNAME', 'username'),
    'PASSWORD': os.getenv('ODOO_PASSWORD', 'password'),
}


# ElasticSearch configuration
CONFIG_ELASTICSEARCH = {
    'HOST': os.getenv('ELASTICSEARCH_HOST', 'https://elastic.uner.gy/elasticsearch/'),
    'USERNAME': os.getenv('ELASTICSEARCH_USERNAME', 'elastic'),
    'PASSWORD': os.getenv('ELASTICSEARCH_PASSWORD', ''),
    'INDEX': os.getenv('ELASTICSEARCH_INDEX', 'prod-backend-factos-logs'),
    'ENABLED': os.getenv('ELASTICSEARCH_ENABLED', 'True').lower() == 'true',
}