# Generated by Django 6.0.2 on 2026-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['sheet_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='invoicesession',
            options={'verbose_name': 'Sesión de factura', 'verbose_name_plural': 'Sesiones de factura'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='cellphone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sheet_name',
            field=models.CharField(max_length=100, verbose_name='Hoja de cálculo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='cellphone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='cost_center',
            field=models.TextField(blank=True, null=True, verbose_name='Centro de costos'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de factura'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='last_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de fila'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='last_row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Última fila'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='state',
            field=models.CharField(choices=[('idle', 'Inactivo'), ('processing_invoice', 'Procesando factura'), ('waiting_cost_center', 'Esperando centro de costos'), ('waiting_concept', 'Esperando concepto')], default='idle', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='invoicesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
