# Generated by Django 6.0.2 on 2026-03-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesession',
            name='state',
            field=models.CharField(choices=[('idle', 'Inactivo'), ('processing_invoice', 'Procesando factura'), ('waiting_confirmation', 'Esperando confirmación'), ('waiting_correction', 'Esperando corrección de valor'), ('waiting_cost_center', 'Esperando centro de costos'), ('waiting_concept', 'Esperando concepto')], default='idle', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellphone', models.CharField(max_length=15, verbose_name='Celular')),
                ('invoice_date', models.CharField(blank=True, default='', max_length=20, verbose_name='Fecha factura')),
                ('business_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Comercio')),
                ('nit', models.CharField(blank=True, default='', max_length=50, verbose_name='NIT')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='N° de factura')),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor original (IA)')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor final')),
                ('was_corrected', models.BooleanField(default=False, verbose_name='Valor corregido por usuario')),
                ('cost_center', models.CharField(blank=True, default='', max_length=255, verbose_name='Centro de costos')),
                ('concept', models.TextField(blank=True, default='', verbose_name='Concepto')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Ruta archivo')),
                ('is_pdf', models.BooleanField(default=False, verbose_name='Es PDF')),
                ('sheet_row', models.IntegerField(blank=True, null=True, verbose_name='Fila en Sheets')),
                ('sheet_record_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID fila en Sheets')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmada'), ('abandoned', 'Abandonada'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoicesession',
            name='current_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.invoice', verbose_name='Factura actual'),
        ),
    ]
