# Generated by Django 6.0.2 on 2026-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_and_session_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sheet_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Hoja de cálculo'),
        ),
    ]
