# Generated by Django 6.0.2 on 2026-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha factura'),
        ),
    ]
