# Generated by Django 6.0.2 on 2026-03-06 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ID carpeta Drive'),
        ),
        migrations.CreateModel(
            name='PettyReload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Referencia')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto solicitado')),
                ('state', models.CharField(choices=[('draft', 'Solicitud'), ('approved', 'Aprobado'), ('executed', 'Realizado'), ('cancel', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('date_request', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reloads', to='core.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Recarga de Caja Menor',
                'verbose_name_plural': 'Recargas de Caja Menor',
                'ordering': ['-date_request'],
            },
        ),
    ]
