# Generated by Django 6.0.2 on 2026-03-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_drive_folder_id_pettyreload'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cupo Mensual'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_odoo_doc',
            field=models.BooleanField(default=False, verbose_name='Check Odoo Doc'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_odoo_pago',
            field=models.BooleanField(default=False, verbose_name='Check Odoo Pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cufe',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CUFE'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
    ]
