# Generated by Django 5.2 on 2025-07-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the email in Gmail', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('from_email', models.CharField(help_text='Email address of the sender', max_length=255)),
                ('thread_id', models.CharField(help_text='Thread ID for the email conversation', max_length=255)),
                ('label_ids', models.JSONField(default=list, help_text='List of label IDs associated with the email')),
                ('snippet', models.TextField(help_text='Short snippet of the email content')),
                ('payload', models.JSONField(help_text='Payload of the email containing headers and body')),
                ('size_estimate', models.IntegerField(help_text='Estimated size of the email in bytes')),
                ('history_id', models.CharField(help_text='History ID for tracking changes to the email', max_length=255)),
                ('internal_date', models.DateTimeField(help_text='Internal date of the email in milliseconds since epoch')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('attachment_id', models.CharField(help_text='Unique identifier for the attachment', max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Attachment file', upload_to='email_attachments/')),
                ('filename', models.CharField(help_text='Name of the attachment file', max_length=255)),
                ('content_type', models.CharField(choices=[('application/x-pdf', 'PDF'), ('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('application/zip', 'ZIP')], help_text='MIME type of the attachment', max_length=50)),
                ('size', models.IntegerField(help_text='Size of the attachment in bytes')),
                ('email', models.ForeignKey(help_text='Email to which the attachment belongs', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails_reader.email')),
            ],
        ),
    ]
